@baseUrl = http://localhost:3000

# RECADOS
### Lista todos os recados
GET {{baseUrl}}/recados/
?limit=10
&offset=0
### Lista apenas um recado
GET {{baseUrl}}/recados/30/
### Cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "De Leo para Joana",
    "deId": 14,
    "paraId": 12
}
### Atualiza um recado
PATCH {{baseUrl}}/recados/1/
Content-Type: application/json

{
    "texto": "De Leo para Joana",
    "lido": false
}
### Apaga um recado
DELETE {{baseUrl}}/recados/5/



# 



# Pessoas
### Lista todas as pessoas
GET {{baseUrl}}/pessoas/
?limit=10
&offset=0
### Lista apenas uma pessoa
GET {{baseUrl}}/pessoas/3/
### Cria uma pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
    "email": "leo@email.com",
    "password": "123456",
    "nome": "leo"
}
### Atualiza uma pessoa
PATCH {{baseUrl}}/pessoas/10/
Content-Type: application/json

{
    "password": "aaaaaa"
}
### Apaga uma pessoa
DELETE {{baseUrl}}/pessoas/10/



#


### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### ExemploDeRota

# @name ExemploDeRota
GET {{baseUrl}}/home/exemplo/

### ConceitosManualController Home

# @name ConceitosManualControllerHome
GET {{baseUrl}}/conceitos-manual/

### ConceitosAutomaticoController Home

# @name ConceitosAutomaticoControllerHome
GET {{baseUrl}}/conceitos-automatico/
